name: markdown_quill
description: Convert between quill (delta) format and markdown
version: 2.0.0
repository: https://github.com/TarekkMA/markdown_quill

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.17.1
  flutter_quill: ^7.2.6
  markdown: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.7.0
  very_good_analysis: ^2.4.0
