name: markdown_quill
description: Convert between quill (delta) format and markdown
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  charcode: ^1.3.1
  flutter:
    sdk: flutter
  flutter_quill: ^2.0.20
  markdown: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
  meta: ^1.7.0